---
meta:
  name:   load-balancer
  target: genesis@pipes
  url:    https://pipes.starkandwayne.com

  initial_version: 0.0.1

  git:
    name: Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  github:
    owner: genesis-community
    repo: load-balancer-boshrelease
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  bosh-lite:
    target:   ((bosh.uri))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
